version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wpt-bap-tn-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ouhoyouxj575"
s3_prefix = "wpt-bap-tn-2"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "UserResidentTableName=\"wpt.bap.tn.user-resident-rev2\" UserTableName=\"wpt.bap.tn.user-rev1\" CheckpointTableName=\"wpt.bap.tn.checkpoint-rev3\" RouteTableName=\"wpt.bap.tn.route-rev1\" VerseTableName=\"wpt.bap.tn.verse-rev1\" UserResidentBucketName=\"wpt.bap.tn.resident.names\" Region=\"us-east-1\" AccessKeyId=\"AKIA4AZLILU45MCHT4XP\" SecretAccessKey=\"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\" DbEnv=\"prod\""
