version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wpt-bap-tn"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ouhoyouxj575"
s3_prefix = "wpt-bap-tn"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
