    # FROM lambci/lambda:build-ruby2.7
    FROM public.ecr.aws/sam/build-ruby2.7:latest-x86_64
    # RUN yum -y install mysql-devel
    # RUN gem update bundler
    # RUN bundler -v
    # RUN bundle config --local deployment 'false'
    # RUN bundle install
    # RUN bundle config --local deployment 'true'
    # RUN bundle install
    CMD "/bin/bash"