source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'sinatra-cors'
gem 'sequel'
gem 'mysql2'
gem 'aws-sdk-kms'
gem 'base64'
gem 'aws-record'
# gem "sinatra-contrib",require: false
# gem 'json'
# gem 'dotenv'
# gem 'sinatra-sequel'
